### ISSUE TITLE
GLXOSD with Unigine Tropics - received invalid memory reference signal

### ISSUE THREAD

**Issue by WojtasJD** [nickguletskii/GLXOSD#62] opened 2016-02-03 21:54 UTC
Hello,
Ubuntu 14.04.3 LTS 64-bit with installed Unigine Tropics for GNU/Linux:
https://unigine.com/en/products/benchmarks/tropics
http://www.techspot.com/downloads/5802-unigine-tropics-benchmark.html

and GLXOSD of course ( https://glxosd.nickguletskii.com/install.html ) - tested with glxgears

Tropics demo is working fine by executing script file like _./1600x1200_fullscreen.sh_

```
#!/bin/sh

export LD_LIBRARY_PATH=./bin:$LD_LIBRARY_PATH
./bin/Tropics		-video_app opengl \
					-sound_app openal \
					-extern_define RELEASE \
					-system_script tropics/unigine.cpp \
					-engine_config ../data/unigine.cfg \
					-data_path ../ \
					-video_fullscreen 1 \
					-video_mode -1 \
					-video_width 1600 \
					-video_height 1200
```

but with GLXOSD it cannot run - attached log file.
[glxosd_tropics.txt](https://github.com/nickguletskii/GLXOSD/files/116466/glxosd_tropics.txt

**Comment by licaon-kter** [comment] 2016-02-03 22:53
I can confirm with: Sanctuary, Tropics, Heaven 2.5
Works ok with: Heaven 3.0, Heaven 4.0 and Valley

**Comment by nickguletskii** [comment] 2016-03-30 20:36
During the development of GLXOSD v3, I used the latest Uniengine Heaven as a test case. It seems to work for me now. Could you please confirm that version 3 fixes the issues with other Uniengine benchmarks and games too?

**Comment by licaon-kter** [comment] 2016-03-31 22:18
3.0.2:
* Sanctuary/Tropics: `Lua error: /usr/share/glxosd///glxosd/ffi/init.lua:41: libGLEW.so.1.10: cannot open shared object file: No such file or directory`
* Heaven 2.5: https://gist.github.com/licaon-kter/2b3e9ed729d7245f637896dd73a52081

**Comment by nickguletskii** [comment] 2016-04-01 13:36
Sanctuary works fine if you install libGLEW. I seem to have forgotten to add it to the Ubuntu package dependencies. I am fixing this right now.

Tropics and Heaven are *ancient*. I dug them up and they ship with ancient libfreetype statically linked, so I can't do much about them. I am going to close this issue because there isn't much I can do without using `dlmopen` (which doesn't work at the moment).

**Closed by nickguletskii** 2016-04-01 13:36 UTC
Labels: awaiting confirmation, bug, fix released
