### ISSUE TITLE
Metro 2033 redux - text is black

### ISSUE THREAD

**Issue by liamdawe** [nickguletskii/GLXOSD#18] opened 2014-12-12 02:11 UTC
As the title says, the text turns up in black blocks?
http://i.imgur.com/TM5byU8.jpg

**Comment by myromance123** [comment] 2015-01-06 11:44
This also occurs for Metro Last Light Redux. I'm on Ubuntu 14.10 64bit with a GTX 680.

Note that with the 346.22 drivers, Metro Redux (both games) have severe lighting issues (white light seems to pervade the world). I'm unsure if that has anything to do with this however, just informing you in case.

I've also tested the 340.65 drivers (no white light issue), and the GLXOSD text is still black. If there's anything you want me to test, or need output, guide me on it and I'll try to provide it for you. Keep up the good work :)

**Comment by licaon-kter** [comment] 2015-01-06 18:28
@myromance123: you are seeing this bug: https://devtalk.nvidia.com/default/topic/795600/linux/metro-redux-driver-346-xx-very-high-quality-glitch/

offtopic: Steam (in Beta) got FPS display and with corner selection today, it's not GLXOSD, missing hardware sensors and such, but it helps.

**Comment by myromance123** [comment] 2015-01-07 06:10
> The benchmark mode has an included FPS counter, or did I misunderstand what you said?

You are correct that it has an FPS counter in the benchmark. However, for my purposes, said counter is small, and often blends in with the background. GLXOSD allows me to resize the fonts to mega size and appropriately position the counter, which is what I need when I record the benchmarks :)

**Comment by scrawl** [comment] 2015-08-31 00:25
Also happens for me in Middle Earth: Shadow of Mordor.

**Comment by myromance123** [comment] 2015-08-31 05:49
To further add, it now also happens for Company of Heroes 2. It's black boxes where the text should be. This is on the latest Nvidia 355.06 drivers on Ubuntu 15.04 64bit.

**Comment by scrawl** [comment] 2015-08-31 12:14
> Might be a problem with lighting. Possible fix: call glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_DECAL) before rendering.

Just tried this, no change.

<pre>
diff --git a/src/glinject/syncopengl.hpp b/src/glinject/syncopengl.hpp
index 55e89d1..3bbcee3 100644
--- a/src/glinject/syncopengl.hpp
+++ b/src/glinject/syncopengl.hpp
@@ -251,3 +251,5 @@ SYNCHRONIZE_FUNCTION_VOID_RET(glGenTextures, (GLsizei n, GLuint *arrays), (n, ar
 GLOBALLY_SYNCHRONIZE_FUNCTION_VOID_RET(glBindBuffer,(GLuint target, GLuint buffer), (target,buffer))
 GLOBALLY_SYNCHRONIZE_FUNCTION_VOID_RET(glBindVertexArray, (GLuint array), (array))
 GLOBALLY_SYNCHRONIZE_FUNCTION_VOID_RET(glUseProgram,(GLuint program), (program))
+GLOBALLY_SYNCHRONIZE_FUNCTION_VOID_RET(glColor4f,(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha), (red, green, blue, alpha))
+GLOBALLY_SYNCHRONIZE_FUNCTION_VOID_RET(glTexEnvi,(GLenum target, GLenum pname, GLint param), (target, pname, param))
diff --git a/src/glxosd/OSDInstance.cpp b/src/glxosd/OSDInstance.cpp
index 952aac9..8d03bf4 100644
--- a/src/glxosd/OSDInstance.cpp
+++ b/src/glxosd/OSDInstance.cpp
@@ -239,6 +239,9 @@ void OSDInstance::render(unsigned int width, unsigned int height) {
 	rgl(GetIntegerv)(GL_ELEMENT_ARRAY_BUFFER_BINDING,
 			&elementArrayBufferBinding);
 
+    rgl(Color4f)(1,1,1,1);
+    rgl(TexEnvi)(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_DECAL);
+
 	renderText(width, height);
 
 	//Revert buffer states
</pre>

I'm wondering if this could be an issue with GL3 core contexts. I see that GLXOSD renders using the fixed pipeline, which wouldn't work in a GL3 core context.

**Comment by scrawl** [comment] 2015-08-31 12:46
> I'm wondering if this could be an issue with GL3 core contexts. I see that GLXOSD renders using the fixed pipeline, which wouldn't work in a GL3 core context.

In https://github.com/skeeto/opengl-demo , a GL3 core application, GLXOSD seems to work.


![glxosd](https://cloud.githubusercontent.com/assets/720642/9578984/f56a5f98-4fee-11e5-8b84-08c46af24556.png)

**Comment by scrawl** [comment] 2015-08-31 12:48
>  I see that GLXOSD renders using the fixed pipeline

It actually doesn't, I found the [code](https://github.com/nickguletskii/GLXOSD/blob/master/src/glxosd/VertexBuffer.cpp#L35) code that sets up a shader.

**Comment by nickguletskii** [comment] 2015-08-31 12:51
I'll try searching for the cause this evening using VOGL later today now that I have Metro.

**Comment by scrawl** [comment] 2015-08-31 15:35
Thanks @nickguletskii ! I'm almost certain that it's due to the texture being corrupted or loaded incorrectly. I can get a color to show up if I change the fragment shader to return a solid color.

Fixed function states like GL_TEXTURE_ENV_MODE shouldn't make any difference, since we're rendering with shaders.

**Comment by nickguletskii** [comment] 2015-08-31 16:51
I had a problem with Kerbal Space Program where it would replace my textures with its own. They seem to have hard-coded texture ids. This, however, may not be the case here.

**Comment by nickguletskii** [comment] 2015-08-31 19:49
Found the problem. I will try to deploy a fix tomorrow. I wasn't resetting the sampler (glBindSampler).

**Comment by scrawl** [comment] 2015-09-01 22:01
You were correct, resetting sampler state fixed the bug for me.

<pre>
diff --git a/src/glxosd/OSDInstance.cpp b/src/glxosd/OSDInstance.cpp
index c157a9c..a996245 100644
--- a/src/glxosd/OSDInstance.cpp
+++ b/src/glxosd/OSDInstance.cpp
@@ -223,7 +223,7 @@ void OSDInstance::render(unsigned int width, unsigned int height) {
 	//Memorise buffer states
 	GLint pixelUnpackBufferBinding = 0, arrayBufferBinding = 0, activeTexture =
 			0, textureBinding2D = 0, vertexArrayBinding = 0,
-			elementArrayBufferBinding = 0;
+			elementArrayBufferBinding = 0, sampler = 0;
 	rgl(GetIntegerv)(GL_PIXEL_UNPACK_BUFFER_BINDING,
 			&pixelUnpackBufferBinding);
 	rgl(GetIntegerv)(GL_ARRAY_BUFFER_BINDING, &arrayBufferBinding);
@@ -233,10 +233,14 @@ void OSDInstance::render(unsigned int width, unsigned int height) {
 	rgl(GetIntegerv)(GL_ELEMENT_ARRAY_BUFFER_BINDING,
 			&elementArrayBufferBinding);
 
+	rgl(GetIntegerv)(GL_SAMPLER_BINDING, &sampler);
+	rgl(BindSampler)(0, 0);
+
 	renderText(width, height);
 
 	//Revert buffer states
 	rgl(ActiveTexture)(activeTexture);
+	rgl(BindSampler)(0, sampler);
 	rgl(BindTexture)(GL_TEXTURE_2D, textureBinding2D);
 	rgl(BindVertexArray)(vertexArrayBinding);
 	rgl(BindBuffer)(GL_PIXEL_UNPACK_BUFFER, pixelUnpackBufferBinding);
</pre>

**Comment by nickguletskii** [comment] 2015-09-02 10:34
Should be fixed in version 2.4.0.

**Closed by nickguletskii** 2015-09-02 10:34 UTC
Labels: bug

**Comment by myromance123** [comment] 2015-09-02 11:10
I can confirm this fixes the issue in Shadow Of Mordor, Company of Heroes 2 and Metro Last Light Redux.

Tested on Ubuntu 15.04 64bit with a GTX 680 2GB on Nvidia 355.06 drivers.
