### ISSUE TITLE
Dota2 (steam) always crashes, when run with glxosd

### ISSUE THREAD

**Issue by martin80cz** [nickguletskii/GLXOSD#17] opened 2014-11-01 14:43 UTC
I have Ubuntu 14.04 and GeForce 755M (lenovo ideapad y510p). Dota2 without glxosd runs fine, but when I try glxosd --steam %command% and launch it, all I can see for a second i is a black screen with osd, then crashes ... any others of games launching with glxosd run fine.

**Comment by myromance123** [comment] 2015-01-17 01:00
I can confirm that Dota 2 crashes when adding GLXOSD to the launch options. Dota 2 will crash with a segmentation fault. It happens exactly as martin80cz says.

I'm running discrete graphics on a desktop computer. I've installed GLXOSD via the PPA.
OS: Ubuntu 14.10 64bit
CPU: Intel i7-4770 3.4GHz
GPU: Nvidia GTX680 (346.35 proprietary driver)

**Comment by myromance123** [comment] 2015-01-24 16:25
It would seem that Counter Strike Global Offensive and Chivalry now crash as well. Does this have to do with the newer Nvidia drivers or how things have changed under the hood in Ubuntu 14.10?

Back in Ubuntu 14.04 with older Nvidia drivers I was able to run CS GO with GLXOSD no problem.

**Comment by nickguletskii** [comment] 2015-02-17 19:00
Doesn't seem to happen to me on Kubuntu 14.04 with CS:GO, so I assume this is caused by libstdc++ compatibility issues... I will try Dota 2 tomorrow, but I can't really guarantee a solution any time soon because this issue would require a lot of packaging work and I don't really have that much time right now...

**Comment by nickguletskii** [comment] 2015-03-27 07:18
This bug is directly related to this:

https://github.com/nickguletskii/GLXOSD/issues/24

**Comment by nickguletskii** [comment] 2015-03-29 11:54
I tried CS:GO in Ubuntu 15.04 running in VirtualBox and it worked (after removing Steam's copy of libstdc++). Can you please try removing Steam's libstdc++?

    mv /home/shoof/.steam/ubuntu12_32/steam-runtime/i386/usr/lib/i386-linux-gnu/libstdc++.so.6{,.disable}

**Comment by myromance123** [comment] 2015-04-02 23:20
I renamed the following on Ubuntu 15.04 64bit, and it seems to work now with Dota 2. No crashing on startup anymore, and GLXOSD is able to display itself properly.
```
libstdc++.so.6.0.18
libstdc++.so.6
libgcc_s.so.1
```
<a href="http://imgur.com/FdxBt7L"><img src="http://i.imgur.com/FdxBt7L.png" title="source: imgur.com" /></a>

GLXOSD is still black in Metro and Shadow Warrior though, so that issue seems to be unrelated to this.

**Comment by nickguletskii** [comment] 2016-05-01 21:54
This is fixed in version 3.1.0.

**Closed by nickguletskii** 2016-05-01 21:54 UTC
Labels: bug, library incompatibility
